# Generated by Django 3.0.9 on 2020-10-20 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_message_receiver_sender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.TextField()),
                ('receiver', models.TextField()),
                ('message', models.TextField()),
                ('subject', models.TextField()),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
