# Generated by Django 3.0.9 on 2020-10-21 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0004_message1'),
    ]

    operations = [
        migrations.AddField(
            model_name='message1',
            name='read_by_receiver',
            field=models.BooleanField(default=False),
        ),
    ]
