# Generated by Django 3.0.9 on 2020-10-21 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0006_auto_20201021_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message1',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
