# Generated by Django 3.0.9 on 2020-10-21 07:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0007_auto_20201021_1023'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message1',
        ),
        migrations.AddField(
            model_name='message',
            name='read_by_receiver',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='receiver',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.TextField(),
        ),
    ]
